# This is the primary configuration file for a NeoForge mod.
modLoader = "neoforge"
loaderVersion = "[21,)"
license = "All Rights Reserved"

[[mods]]
modId = "nightmarez"
version = "1.0.0"
displayName = "NightmareZ"
description = '''A new threat appears in the world of Minecraft.'''

# This section tells NeoForge how to load your mod. THIS IS THE FIX.
[tool.neoforge.mods]
nightmarez = {}

# This section declares dependencies for your mod.
[tool.neoforge.dependencies.nightmarez]
neoforge = { versionRange = "[21,)", mandatory = true }
minecraft = { versionRange = "[1.21,)", mandatory = true }