# This is the primary configuration file for a NeoForge mod.
modLoader = "neoforge"
# The version range of the loader that this mod requires.
# The single quotes are important.
loaderVersion = '[21,)'
license = "All Rights Reserved"

[[mods]]
modId = "nightmarez"
# The version variable is populated by the build script.
version = "${version}"
displayName = "NightmareZ"
description = '''A new threat appears in the world of Minecraft.'''

[tool.neoforge.mods]
nightmarez = {}

[tool.neoforge.dependencies.nightmarez]
neoforge = { versionRange = "[21,)", mandatory = true }
minecraft = { versionRange = "[1.21,)", mandatory = true }